#!/bin/bash
echo "Press Ctrl+C to stop the script"
eject
while :
do
  echo "Please insert disc"
  disc=2
  
  while [[ $disc != 0 ]]
  do
    sudo blkid /dev/sr0 >> /dev/null
    disc=$?
    sleep 5 
  done
  
  name=$(sudo blkid /dev/sr0 | cut -d= -f3 | cut -d'"' -f2)
  output=$(echo $name | sed -e 's/ /_/g')
  echo "Disc Found: $name"
  echo "Outputting to: $output.iso"

  # Set save path here
  dd if=/dev/sr0 | pv | dd of=~/ISOs/$output.iso

  echo "Finished! Insert your next disc"
  eject
  sleep 10
done
